# Generated by Django 5.0.4 on 2024-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(auto_now=True)),
                ('dataFinal', models.DateField()),
                ('titulo', models.CharField(max_length=255)),
                ('pauta', models.TextField()),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
